# Example GitHub Actions CI for C++/CMake/Nix project
name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v25
              with:
                  nix_path: nixpkgs=channel:nixos-24.11
            - name: Nix flake check
              run: nix flake check
            - name: Run format check
              run: nix fmt
            - name: Build
              run: nom build
